### ISSUE TITLE
No module named 'idd3'

### ISSUE THREAD

**Issue by JohnSkyReal** [andrecunha/coh-metrix-dementia#8]
I can't install the 'idd3' module or find it at anywhere,
the problem is showing as follows:

Traceback (most recent call last):
  File "/home/dl/HaotianHu/coh-metrix-dementia-master/base.py", line 19, in <module>
    from coh.tools import senter, word_tokenize,\
  File "/home/dl/anaconda3/envs/python34/lib/python3.4/site-packages/Coh_Metrix_Dementia-0.0.1-py3.4.egg/coh/__init__.py", line 34, in <module>
    from coh.metrics import *
  File "/home/dl/anaconda3/envs/python34/lib/python3.4/site-packages/Coh_Metrix_Dementia-0.0.1-py3.4.egg/coh/metrics/__init__.py", line 28, in <module>
    from coh.metrics.sem import *
  File "/home/dl/anaconda3/envs/python34/lib/python3.4/site-packages/Coh_Metrix_Dementia-0.0.1-py3.4.egg/coh/metrics/sem.py", line 19, in <module>
    import idd3
ImportError: No module named 'idd3'

**Comment by lbsantos** [comment]
You can find idd3 here [https://github.com/andrecunha/idd3](url)

**Comment by JohnSkyReal** [comment]
Thank you very much!
